### ISSUE TITLE
No such filter: 'v360

### ISSUE THREAD

**Issue by ethanfel** [michael-mueller-git/Python-Funscript-Editor#2]
```
2021-07-08 23:26:17 Pixeluntu funscript_editor.ui.funscript_editor_window[2442334] INFO Stop at Frame -1
[AVFilterGraph @ 0x556c5f67fe80] '
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0
Traceback (most recent call last):
  File "/home/ethanfel/Python-Funscript-Editor/funscript_editor/algorithms/funscriptgenerator.py", line 955, in run
    status = self.tracking()
  File "/home/ethanfel/Python-Funscript-Editor/funscript_editor/algorithms/funscriptgenerator.py", line 621, in tracking
    projection_config = self.get_vr_projection_config(first_frame)
  File "/home/ethanfel/Python-Funscript-Editor/funscript_editor/algorithms/funscriptgenerator.py", line 503, in get_vr_projection_config
    preview = FFmpegStream.get_projection(image, config)
  File "/home/ethanfel/Python-Funscript-Editor/funscript_editor/data/ffmpegstream.py", line 151, in get_projection
    projection = np.frombuffer(
ValueError: cannot reshape array of size 0 into shape (720,1240,3)
```

doesn't seems to be able to track

**Comment by ethanfel** [comment]
resolved : Ubuntu 20.04 ffmpeg is too old
 using this ppa resolved the issue
https://launchpad.net/~savoury1/+archive/ubuntu/ffmpeg4
