### ISSUE TITLE
'TrackingManagerThread' object has no attribute 'projection_config'

### ISSUE THREAD

**Issue by ZestyRaraferu** [michael-mueller-git/Python-Funscript-Editor#24]
**Describe the bug**
"Start MTFG" -> "Okay". The popup closes but nothing happens. Logs contains the following error message:
```
2024-05-23 18:02:15,170 - funscript_editor.api - INFO - Python Funscript Generator 0.5.4
2024-05-23 18:02:15,170 - funscript_editor.api - INFO - Startup Path: C:\Portable Apps\Scripty\OFS3
2024-05-23 18:02:15,170 - funscript_editor.api - INFO - Args: video_file=C:\Portable Apps\Scripty\OFSProject\20240523.mkv, start_time=0.0, end_time=-1.0, output_file=C:\Users\****\AppData\Roaming\OFS\OFS3_data\extensions\Funscript Generator Windows/funscript_actions.json
2024-05-23 18:02:15,355 - funscript_editor.ui.funscript_generator_window - INFO - Set End Time to Frame Number -1
2024-05-23 18:02:15,355 - funscript_editor.ui.funscript_generator_window - INFO - Hyperparameter:{'min_frames': 90, 'user_reaction_time_in_milliseconds': 800, 'signal': {'avg_sec_for_local_min_max_extraction': 2.0, 'min_evenly_intermediate_interframes': 2}, 'scene_detector': {'min_scene_len_in_seconds': 3, 'scene_content_detector_threshold': 30.0, 'scene_threshold_detector_threshold': 12}, 'tracker': {'tracking_init_phase_in_sec': 6, 'tracking_plausibility_factor_x': 4.0, 'tracking_plausibility_factor_y': 2.5}}
2024-05-23 18:02:15,355 - funscript_editor.ui.funscript_generator_window - INFO - Config:{'use_zoom': False, 'zoom_factor': 4.0, 'max_playback_fps': 0, 'preview_scaling': 0.6, 'tracker': 'CSRT', 'notification_sound': 'off', 'scene_detector': 'CSV', 'dark_theme': False, 'tracking_plausibility_check': False, 'ffmpeg_timeout_in_seconds': 15, 'open_postprocessing_maximized': True}
2024-05-23 18:02:16,640 - funscript_editor.ui.funscript_generator_window - INFO - settings: {'videoType': '2D Video with Keyboard Menu', 'trackingMetrics': 'y', 'trackingMethod': 'Unsupervised one moving person', 'numberOfTracker': '2', 'processingSpeed': '0', 'outputMode': 'post processed data'}
2024-05-23 18:02:16,740 - funscript_editor.algorithms.trackingmanager - CRITICAL - The program crashed in TrackingManager due to a fatal error
Traceback (most recent call last):
  File "funscript_editor\algorithms\trackingmanager.py", line 762, in run
  File "funscript_editor\algorithms\trackingmanager.py", line 723, in finished
AttributeError: 'TrackingManagerThread' object has no attribute 'projection_config'
```

**Runtime:**
- Windows 11 23H2 22631.3593
- MTFG 0.5.4
- OFS3

**Additional context**
This seems to happen with the specific video I am attempt to use tracking on. It does not happen with other videos.
I have attempted to rename the video, change its directory and re-encoding with AV1, doesn't fix the issue.

Here's a clip for reproducing the issue:
https://litter.catbox.moe/dlbl9p.mp4

**Comment by ZestyRaraferu** [comment]
Update: Re-encoding the video with H.264 seems to fix the issue. It appears like this only happens with AV1 encoded video.

This is the encoder settings for the original video, it was also AV1.
![1297g5NGIt](https://github.com/michael-mueller-git/Python-Funscript-Editor/assets/121066630/134d2510-23f9-4369-ad3a-e2363b1b3bff)

**Comment by michael-mueller-git** [comment]
Hi, Thanks for reporting the bug. The program crashes if it cannot decode the video properly, as you have already discovered. 
I have fixed the error message in [eee779a3492397ade4d53129b9b42f6d50e83ec1](https://github.com/michael-mueller-git/Python-Funscript-Editor/commit/eee779a3492397ade4d53129b9b42f6d50e83ec1) but I have not yet recompiled the code for windows since then. When the windows build pipeline is still working i will create an new release that should display a proper error message...

**Comment by michael-mueller-git** [comment]
Ok release is now available. Would be great if you could test if version [v0.5.5](https://github.com/michael-mueller-git/Python-Funscript-Editor/releases/tag/v0.5.5) shows a normal error message and do not cause a program crash.

**Comment by ZestyRaraferu** [comment]
Appears to be the case now, thanks.
![1323mEk1YO](https://github.com/michael-mueller-git/Python-Funscript-Editor/assets/121066630/e483939b-5b33-461f-a437-aeb16cf4c15f)

**Comment by michael-mueller-git** [comment]
Thanks for the feedback.
